// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: pie-dot-fun/v1/basket-token.proto

/* eslint-disable */
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: pie-dot-fun/v1/common.proto

/* eslint-disable */

export const protobufPackage = "piedotfun.v1";

export enum ChainType {
  /** CHAIN_UNSPECIFIED - Unspecified blockchain type. */
  CHAIN_UNSPECIFIED = "CHAIN_UNSPECIFIED",
  /** SOLANA - Solana Mainnet blockchain. */
  SOLANA = "SOLANA",
  /** SOLANA_TESTNET - Solana Testnet blockchain. */
  SOLANA_TESTNET = "SOLANA_TESTNET",
  /** SOLANA_DEVNET - Solana Devnet blockchain. */
  SOLANA_DEVNET = "SOLANA_DEVNET",
}

export enum VMType {
  /** VM_UNSPECIFIED - Unspecified VM type. */
  VM_UNSPECIFIED = "VM_UNSPECIFIED",
  /** SVM - Solana Virtual Machine. */
  SVM = "SVM",
  /** EVM - Ethereum Virtual Machine. */
  EVM = "EVM",
}

export enum Currency {
  CURRENCY_UNSPECIFIED = "CURRENCY_UNSPECIFIED",
  CURRENCY_SOL = "CURRENCY_SOL",
  CURRENCY_USDC = "CURRENCY_USDC",
}

export enum PnLPeriod {
  PNL_PERIOD_UNSPECIFIED = "PNL_PERIOD_UNSPECIFIED",
  PNL_PERIOD_1_HOUR = "PNL_PERIOD_1_HOUR",
  PNL_PERIOD_24_HOUR = "PNL_PERIOD_24_HOUR",
  PNL_PERIOD_ALL_TIME = "PNL_PERIOD_ALL_TIME",
}

export enum PriceChangePeriod {
  PRICE_CHANGE_PERIOD_UNSPECIFIED = "PRICE_CHANGE_PERIOD_UNSPECIFIED",
  PRICE_CHANGE_PERIOD_1_HOUR = "PRICE_CHANGE_PERIOD_1_HOUR",
  PRICE_CHANGE_PERIOD_24_HOUR = "PRICE_CHANGE_PERIOD_24_HOUR",
  PRICE_CHANGE_PERIOD_7_DAY = "PRICE_CHANGE_PERIOD_7_DAY",
  PRICE_CHANGE_PERIOD_30_DAY = "PRICE_CHANGE_PERIOD_30_DAY",
  PRICE_CHANGE_PERIOD_ALL_TIME = "PRICE_CHANGE_PERIOD_ALL_TIME",
}

export interface Quantity {
  formattedAmount: string;
  rawAmount: string;
  decimals: number;
}

export interface Money {
  currency: Currency;
  formattedAmount: string;
  rawAmount: string;
  decimals: number;
}

export interface Percentage {
  value: number;
}

export interface PnLsByPeriod {
  /** map from period to PnL */
  pnls: { [key: string]: PnL };
}

export interface PnLsByPeriod_PnlsEntry {
  key: string;
  value: PnL | undefined;
}

export interface PnL {
  nominalValue: Money | undefined;
  percentageChange: Percentage | undefined;
  period: PnLPeriod;
}

export interface PriceChange {
  nominalValue: Money | undefined;
  percentageChange: Percentage | undefined;
  period: PriceChangePeriod;
}

export interface PriceChangesByPeriod {
  /** PriceChangePeriod enum sring to PriceChange */
  priceChanges: { [key: string]: PriceChange };
}

export interface PriceChangesByPeriod_PriceChangesEntry {
  key: string;
  value: PriceChange | undefined;
}

export interface SNS {
  type: SNS_SNSType;
  name: string;
  profileUrl: string;
}

export enum SNS_SNSType {
  SNS_TYPE_UNSPECIFIED = "SNS_TYPE_UNSPECIFIED",
  EMAIL = "EMAIL",
  GOOGLE = "GOOGLE",
  TWITTER = "TWITTER",
}

export enum BasketTokenState {
  BASKET_TOKEN_STATE_UNSPECIFIED = "BASKET_TOKEN_STATE_UNSPECIFIED",
  /** BASKET_TOKEN_STATE_CREATED - 온체인 상에서만 생성되고, 아직 우리 서비스에서 리스팅은 되지 않은 상태 */
  BASKET_TOKEN_STATE_CREATED = "BASKET_TOKEN_STATE_CREATED",
  /** BASKET_TOKEN_STATE_LISTED - 우리 서비스에서 리스팅된 상태 */
  BASKET_TOKEN_STATE_LISTED = "BASKET_TOKEN_STATE_LISTED",
}

export enum TokenStrategy {
  TOKEN_STRATEGY_UNSPECIFIED = "TOKEN_STRATEGY_UNSPECIFIED",
  TOKEN_STRATEGY_MARKET_CAP_WEIGHTED = "TOKEN_STRATEGY_MARKET_CAP_WEIGHTED",
  TOKEN_STRATEGY_EQUAL_WEIGHTED = "TOKEN_STRATEGY_EQUAL_WEIGHTED",
  TOKEN_STRATEGY_FACTOR_WEIGHTED = "TOKEN_STRATEGY_FACTOR_WEIGHTED",
  TOKEN_STRATEGY_FUNDAMENTAL_WEIGHTED = "TOKEN_STRATEGY_FUNDAMENTAL_WEIGHTED",
  TOKEN_STRATEGY_RISK_WEIGHTED = "TOKEN_STRATEGY_RISK_WEIGHTED",
  TOKEN_STRATEGY_MOMENTUM_WEIGHTED = "TOKEN_STRATEGY_MOMENTUM_WEIGHTED",
  TOKEN_STRATEGY_CUSTOM_WEIGHTED = "TOKEN_STRATEGY_CUSTOM_WEIGHTED",
}

export enum RebalanceFrequency {
  REBALANCE_FREQUENCY_UNSPECIFIED = "REBALANCE_FREQUENCY_UNSPECIFIED",
  REBALANCE_FREQUENCY_MANUAL = "REBALANCE_FREQUENCY_MANUAL",
  REBALANCE_FREQUENCY_DAILY = "REBALANCE_FREQUENCY_DAILY",
  REBALANCE_FREQUENCY_WEEKLY = "REBALANCE_FREQUENCY_WEEKLY",
  REBALANCE_FREQUENCY_MONTHLY = "REBALANCE_FREQUENCY_MONTHLY",
}

export interface GetBasketTokenRequest {
  /**
   * The name of the basket token to retrieve.
   * Format : "basketTokens/{chain}/{token_address}"
   */
  basketToken: string;
}

/**
 * ListBasketTokensRequest payload
 * (-- api-linter: core::0158::request-page-token-field=disabled
 *     aip.dev/not-precedent: We need to do this because reasons. --)
 * (-- api-linter: core::0132::request-unknown-fields=disabled
 *     aip.dev/not-precedent: We really need this field because reasons. --)
 */
export interface ListBasketTokensRequest {
  /**
   * The maximum number of basket tokens to return. The service may return fewer than
   * this value.
   * If unspecified, at most 50 rows will be returned.
   * The maximum value is 1024; values above 1024 will be coerced to 1024.
   */
  pageSize: number;
  /**
   * Token of the page to retrieve. If not specified, the first
   * page of results will be returned. Use the value obtained from
   * `next_page_token` in the previous response in order to request
   * the next page of results.
   *
   * When paginating, all other parameters provided to `ListBasketTokens` must match
   * the call that provided the page token.
   */
  pageToken: string;
  /**
   * Available Sequence and Operator
   * * name
   *   * `=`
   * * chain
   *   * `=`
   * * display_name
   *   * `=`
   * * ticker
   *   * `=`
   * * state
   *   * `=` (BASKET_TOKEN_STATE_CREATED, BASKET_TOKEN_STATE_LISTED)
   * * market_cap_sol
   *   * `=`, `>`, `<`, `>=`, `<=`
   * * market_cap_usdc
   *   * `=`, `>`, `<`, `>=`, `<=`
   *
   * Examples
   * * name="basketTokens/SOLANA/FZ4MT1HYJHd9GK8D5mJ9f3r7irLaDL5NxBNLjGqrLqs9"
   * * chain=SOLANA
   * * ticker="MURAD"
   * * state=BASKET_TOKEN_STATE_LISTED
   * * market_cap_sol>=1000000
   */
  filter: string;
  /**
   * One or more fields to compare and use to sort the output. (optional)
   * Default order for a field is descending by id
   * To specify ascending or descending order, append " asc" or " desc" to the field name. If not specified, the order is ascending.
   *
   * Reference
   * * https://google.aip.dev/132#ordering.
   *
   * Supported Fields
   * * "market_cap", "create_date"
   *
   * Examples
   * * order_by=create_date desc
   * * order_by=market_cap desc
   */
  orderBy: string;
}

export interface ListBasketTokensResponse {
  basketTokens: BasketToken[];
  /**
   * Pagination token used to retrieve the next page of results.
   * Pass the content of this string as the `page_token` attribute of
   * the next request. `next_page_token` is not returned for the last
   * page.
   */
  nextPageToken: string;
}

export interface ListRebalancingHistoriesRequest {
  /**
   * The name of the basket token to retrieve.
   * Format : "basketTokens/{chain}/{token_address}"
   */
  basketToken: string;
  /**
   * The maximum number of histories to return. The service may return fewer than
   * this value.
   * If unspecified, at most 50 rows will be returned.
   * The maximum value is 1024; values above 1024 will be coerced to 1024.
   */
  pageSize: number;
  /**
   * Token of the page to retrieve. If not specified, the first
   * page of results will be returned. Use the value obtained from
   * `next_page_token` in the previous response in order to request
   * the next page of results.
   *
   * When paginating, all other parameters provided to `ListUsers` must match
   * the call that provided the page token.
   */
  pageToken: string;
}

export interface ListRebalancingHistoriesResponse {
  rebalancingHistories: BasketTokenRebanlancingHistory[];
  /**
   * Pagination token used to retrieve the next page of results.
   * Pass the content of this string as the `page_token` attribute of
   * the next request. `next_page_token` is not returned for the last
   * page.
   */
  nextPageToken: string;
}

export interface BasketToken {
  /** Format : "basketTokens/{chain}/{token_address}" */
  name: string;
  chain: ChainType;
  address: string;
  displayName: string;
  ticker: string;
  iconImageUri: string;
  state: BasketTokenState;
  /** Metadata of the token which is stored in the Solana program token metadata */
  metadata: TokenMetadata | undefined;
  components: Component[];
  createTime: string | undefined;
  expireTime: string | undefined;
  lastRebalanceTime: string | undefined;
}

export interface Component {
  /** Format : "fungibleTokens/{chain}/{token_address}" */
  fungibleToken: string;
  chain: ChainType;
  address: string;
  /**
   * The weight of the component in the basket token.
   * The weight is a percentage of the total value within the basket token. (0.0 ~ 100.0 %)
   */
  weight: Percentage | undefined;
}

export interface TokenMetadata {
  description: string;
  strategy: TokenStrategy;
  rebalanceFrequency: RebalanceFrequency;
  mintFee: number;
}

export interface BasketTokenRebanlancingHistory {
  tokenAddress: string;
  rebalanceTime: string | undefined;
}

/** BasketTokenService contains the function to interact with the BasketToken of the spacebar */
export interface BasketTokenService {
  GetBasketToken(request: GetBasketTokenRequest): Promise<BasketToken>;
  ListBasketTokens(
    request: ListBasketTokensRequest,
  ): Promise<ListBasketTokensResponse>;
  ListBasketTokenRebalancingHistories(
    request: ListRebalancingHistoriesRequest,
  ): Promise<ListRebalancingHistoriesResponse>;
}
